ShauliBlog/Models/Post.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace ShauliBlog.Models
{
    public enum Category
    {
        Sport,
        Blog,
        News,
        Entertainment
    }
    public class Post : IComparable<Post>
    {
        [Key]
        public int Id { get; set; }

        [Required]
        [Display(Name = "Post Headline")]
        public string Headline { get; set; }

        [Required]
        [Display(Name = "Author")]
        public string Author { get; set; }

        [Required]
        [Display(Name = "Author's website")]
        public string Website { get; set; }

        [Required]
        [Display(Name = "Publicity date")]
        [DataType(DataType.Date)]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd/MM/yyyy}")]
        public DateTime Timestamp { get; set; }

        [Required]
        [Display(Name = "Content")]
        [DataType(DataType.MultilineText)]
        public string Content { get; set; }

        [Display(Name = "Post comments")]
        public List<Comment> Comments{ get; set; }

        public Category Category { get; set; }

        public int CompareTo(Post other)
        {
            return (DateTime.Compare(other.Timestamp, this.Timestamp));
        }
    }
}

ShauliBlog/Controllers/PostsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ShauliBlog.Models;
using System.IO;
using System.Globalization;
using System.Web.Routing;

namespace ShauliBlog.Controllers
{
    [Authorize]
    public class PostsController : Controller
    {
        private BlogDb db = new BlogDb();

        // GET: /Posts/
        public ActionResult Index()
        {
            List<Post> posts = db.Posts.ToList();
            posts.Sort();

            return View(posts);
        }

        public ActionResult Get()
        {
            return Json(db.Posts.ToList());
        }

        // GET: /Posts/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            
            Post post = db.Posts.Include(currPost => currPost.Comments).Where(currPost => currPost.Id == id).FirstOrDefault();

            if (post == null)
            {
                return HttpNotFound();
            }
            return View(post);
        }

        // GET: /Posts/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: /Posts/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Headline,Author,Website,Timestamp,Content,Category")] Post post, HttpPostedFileBase picture, HttpPostedFileBase video)
        {
            if (ModelState.IsValid)
            {
                post.Timestamp = DateTime.Now;
                db.Posts.Add(post);
                db.SaveChanges();

                if (picture != null && picture.ContentLength > 0)
                {
                    string fileName = post.Id + ".png";
                    picture.SaveAs(Server.MapPath("~/Uploads/" + fileName));
                }

                if (video != null && video.ContentLength > 0)
                {
                    string fileName = post.Id + ".mp4";
                    video.SaveAs(Server.MapPath("~/Uploads/" + fileName));
                }
                
 
                return RedirectToAction("Index");
            }


            return View(post);
        }

        // GET: /Posts/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Post post = db.Posts.Find(id);
            if (post == null)
            {
                return HttpNotFound();
            }
            return View(post);
        }

        // POST: /Posts/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include="Id,Headline,Author,Website,Timestamp,Content,Category")] Post post)
        {
            if (ModelState.IsValid)
            {
                db.Entry(post).State = EntityState.Modified;
                db.Entry(post).Property("Timestamp").IsModified = false;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(post);
        }

        // GET: /Posts/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Post post = db.Posts.Find(id);
            if (post == null)
            {
                return HttpNotFound();
            }
            return View(post);
        }

        // POST: /Posts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Post post = db.Posts.Find(id);
            db.Posts.Remove(post);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Search(int? id, string author, string text, string postedAfter, string postedBefore)
        {
            List<Post> results = db.Posts.Include(post => post.Comments).ToList();
            DateTime date;

            // Checks whether to filter by id
            if (id.HasValue)
            {
                results = results.Where(post => post.Id == id.Value).ToList();
            }

            // Checks whether to filter by author
            if (!string.IsNullOrWhiteSpace(author))
            {
                results = results.Where(post => post.Author.Contains(author)).ToList();
            }

            // Checks whether to filter by some sort of text
            if (!string.IsNullOrWhiteSpace(text))
            {
                results = results.Where(post => post.Headline.Contains(text) || post.Content.Contains(text)).ToList();
            }

            // Checks whether to get posts posted after a certain date
            if (postedAfter != null && DateTime.TryParseExact(postedAfter, "yyyy-MM-dd", CultureInfo.InvariantCulture, DateTimeStyles.None, out date))
            {
                results = results.Where(post => post.Timestamp > date).ToList();
            }

            // Checks whether to get posts posted before a certain date
            if (postedBefore != null && DateTime.TryParseExact(postedBefore, "yyyy-MM-dd", CultureInfo.InvariantCulture, DateTimeStyles.None, out date))
            {
                results = results.Where(post => post.Timestamp < date).ToList();
            }

            results.Sort();

            return View("../Blog/Index", results);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ShauliBlog/Controllers/SearchController.cs
using ShauliBlog.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;

namespace ShauliBlog.Controllers
{
    public class SearchController : Controller
    {
        private BlogDb db = new BlogDb();

        // GET: Search
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult JoinPostComments(string postText, string commentText)
        {
            if (string.IsNullOrWhiteSpace(postText) || string.IsNullOrWhiteSpace(commentText))
            {
                return RedirectToAction("Index", "Blog");
            }
            else
            {
                // Creates all possible combinations of post-comments pairs
                var results = (from post in db.Posts
                               join
                                   comment in db.Comments on
                                   post.Id equals comment.PostId

                               select new
                               {
                                   PostId = post.Id,
                                   PostHeadline = post.Headline,
                                   PostText = post.Content,
                                   CommentHeadline = comment.Headline,
                                   CommentText = comment.Content
                               });

                // Gets only the results of posts AND comments containing the text in headling or content
                results = results.Where(pc => ((pc.CommentHeadline.Contains(commentText)) || (pc.CommentText.Contains(commentText))) &&
                                    ((pc.PostText.Contains(postText)) || (pc.PostText.Contains(postText))));

                // Gets the posts that satisfied the conditions.
                List<Post> posts = db.Posts.Include(post => post.Comments).ToList();
                posts = posts.Where(post => results.Any(result => result.PostId == post.Id)).ToList();

                return View("../Blog/Index", posts); 
            }
        }

        public ActionResult GetPostsByCategory(int category)
        {
            Category cat = (Category)category;

            var posts = db.Posts.ToList();

            // Gets the posts by category
            var postsByCategory =
              from post in posts
              group post by post.Category into g
              select new { Category = g.Key, Posts = g.ToList() };

            // Gets only the posts of the requested category
            posts = postsByCategory.Where(c => c.Category == cat).First().Posts;

            return View("../Blog/Index", posts);
        }
    }
}

ShauliBlog/Views/Posts/Create.cshtml
@model ShauliBlog.Models.Post

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<script src="~/Scripts/Posts/create.js"></script>

<h2>Create</h2>

<div class="mainDiv">

    @using (Html.BeginForm("Create", "Posts", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>Post</h4>
            <hr />
            @Html.ValidationSummary(true)

            <div class="form-group">
                @Html.LabelFor(model => model.Headline, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Headline)
                    @Html.ValidationMessageFor(model => model.Headline)
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Author, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Author)
                    @Html.ValidationMessageFor(model => model.Author)
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Website, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Website)
                    @Html.ValidationMessageFor(model => model.Website)
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Content, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Content)
                    @Html.ValidationMessageFor(model => model.Content)
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Category, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EnumDropDownListFor(model => model.Category, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.Category, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <input id="image_checkbox" type="checkbox" class="checkbox" onclick="ImageCheckbox()" checked />
                @Html.Label("Choose image", new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <input id="image" type="file" name="picture" accept="image/*" />
                </div>
            </div>

            <div class="form-group">
                <input id="video_checkbox" type="checkbox" class="checkbox" onclick="VideoCheckbox()" checked />
                @Html.Label("Choose video", new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <input id="video" type="file" name="video" accept="video/*" />
                </div>
            </div>


            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </div>
    }

</div>

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

ShauliBlog/Views/Posts/Delete.cshtml
@model ShauliBlog.Models.Post

@{
    ViewBag.Title = "Delete Post";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete Post</h2>

<h3>Are you sure you want to delete this post?</h3>
<div>
    <h4>Post</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Headline)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Headline)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Author)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Author)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Website)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Website)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Timestamp)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Timestamp)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Content)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Content)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

ShauliBlog/Views/Posts/Details.cshtml
@model ShauliBlog.Models.Post

@{
    ViewBag.Title = "Post Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div class="mainDiv">
    <h4>Post</h4>
	<hr />
    <section>
        <article class="blogPost">
            <header>
                <h2>@Model.Headline</h2>
                <p>
                    <p>Category: @Html.ActionLink(Model.Category.ToString(), "GetPostsByCategory", "Search", new { category = (int)Model.Category }, null)</p>
                    <p>
                        Posted on <time datetime="2009-06-29T23:31+01:00">@Model.Timestamp</time> by <a href="@Model.Website">@Model.Author</a> - 
                            @{if (Model.Comments != null)
                            {@Model.Comments.Count}
                            else
                            { <label>0</label> }} comments
                        
                    </p>
                </p>
            </header>
            <div>

                @{ if (File.Exists(Server.MapPath("~/Uploads/" + Model.Id + ".png")))
                 {
                    <img src="~/Uploads/@(Model.Id).png" />
                 }
                }


                @{
                    foreach (string par in @Model.Content.Split(Environment.NewLine.ToArray()))
                    {
                        <p>@par</p>
                    }

                }

                @{ if (File.Exists(Server.MapPath("~/Uploads/" + Model.Id + ".mp4")))
                 {
                    <video controls="controls">
                        <source src="~Uploads/@(Model.Id).mp4" type="video/mp4" />
                        Your browser does not support the video tag.
                    </video>
                 }
                }

            </div>
        </article>
    </section>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

ShauliBlog/Views/Posts/Edit.cshtml
@model ShauliBlog.Models.Post

@{
    ViewBag.Title = "EditPost";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Post</h4>
        <hr />
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Headline, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Headline)
                @Html.ValidationMessageFor(model => model.Headline)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Author, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Author)
                @Html.ValidationMessageFor(model => model.Author)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Website, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Website)
                @Html.ValidationMessageFor(model => model.Website)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Content, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Content)
                @Html.ValidationMessageFor(model => model.Content)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Category, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.Category, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Category, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

ShauliBlog/Views/Posts/Index.cshtml
@model IEnumerable<ShauliBlog.Models.Post>

@{
    ViewBag.Title = "All Posts";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Posts</h2>
<div class="mainDiv">
    <p>
        @Html.ActionLink("Create New Post", "Create")
    </p>
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Headline)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Author)
            </th>          
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Headline)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Author)
                </td>                
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                    @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.Id }) | 
                    @Html.ActionLink("Comments", "Index", "Comments", new { id = item.Id }, null)
                </td>
            </tr>
        }

    </table>
</div>