ShauliBlog/Controllers/BlogController.cs
using ShauliBlog.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;

namespace ShauliBlog.Controllers
{
    public class BlogController : Controller
    {
        private BlogDb db = new BlogDb();

        // GET: Blog
        public ActionResult Index()
        {
            List<Post> posts = db.Posts.Include(post => post.Comments).ToList();
            posts.Sort();

            return View(posts);
        }
    }
}

ShauliBlog/Controllers/SearchController.cs
using ShauliBlog.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;

namespace ShauliBlog.Controllers
{
    public class SearchController : Controller
    {
        private BlogDb db = new BlogDb();

        // GET: Search
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult JoinPostComments(string postText, string commentText)
        {
            if (string.IsNullOrWhiteSpace(postText) || string.IsNullOrWhiteSpace(commentText))
            {
                return RedirectToAction("Index", "Blog");
            }
            else
            {
                // Creates all possible combinations of post-comments pairs
                var results = (from post in db.Posts
                               join
                                   comment in db.Comments on
                                   post.Id equals comment.PostId

                               select new
                               {
                                   PostId = post.Id,
                                   PostHeadline = post.Headline,
                                   PostText = post.Content,
                                   CommentHeadline = comment.Headline,
                                   CommentText = comment.Content
                               });

                // Gets only the results of posts AND comments containing the text in headling or content
                results = results.Where(pc => ((pc.CommentHeadline.Contains(commentText)) || (pc.CommentText.Contains(commentText))) &&
                                    ((pc.PostText.Contains(postText)) || (pc.PostText.Contains(postText))));

                // Gets the posts that satisfied the conditions.
                List<Post> posts = db.Posts.Include(post => post.Comments).ToList();
                posts = posts.Where(post => results.Any(result => result.PostId == post.Id)).ToList();

                return View("../Blog/Index", posts); 
            }
        }

        public ActionResult GetPostsByCategory(int category)
        {
            Category cat = (Category)category;

            var posts = db.Posts.ToList();

            // Gets the posts by category
            var postsByCategory =
              from post in posts
              group post by post.Category into g
              select new { Category = g.Key, Posts = g.ToList() };

            // Gets only the posts of the requested category
            posts = postsByCategory.Where(c => c.Category == cat).First().Posts;

            return View("../Blog/Index", posts);
        }
    }
}

ShauliBlog/Controllers/StatisticsController.cs
using ShauliBlog.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ShauliBlog.Controllers
{
    public class StatisticsController : Controller
    {
        private BlogDb db = new BlogDb();

        // GET: Statistics
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Categories()
        {
            return View();
        }

        public ActionResult PopularPosts()
        {
            return View();
        }

        public ActionResult PublicityDivisionByCategory()
        {
            var posts = db.Posts.ToList();
            // Gets the posts by category
            
            var postsByCategory =
              from post in posts
              group post by post.Category into g
              select new { Category = g.Key.ToString() + " - " + g.ToList().Count().ToString(), 
                           Posts = g.ToList().Count(),
                           Id = (int)g.Key};

            return Json(postsByCategory.ToList());
        }

        public ActionResult GetPopularComments()
        {
            // Creates all possible combinations of post-comments pairs
            var results = (from post in db.Posts
                           join
                               comment in db.Comments on
                               post.Id equals comment.PostId into postComments

                           select new
                           {
                               Post = post.Headline + " by " + post.Author,
                               CommentsCount = postComments.Count(),
                               Id = post.Id
                           });

            // Gets the top 5 posts.
            results = results.Where(post => post.CommentsCount != 0).OrderByDescending(post => post.CommentsCount).Take(5);

            return Json(results.ToList());
        }
    }
}

ShauliBlog/Views/Blog/Index.cshtml
@model List<ShauliBlog.Models.Post>

@{
    ViewBag.Title = "Blog";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<script src="~/Scripts/Blog/blog.js"></script>

<div id="mainContent">
    @if (Model.Count == 0)
    {
        <div>No posts found.</div>
    }
    else
    {
        foreach (ShauliBlog.Models.Post post in Model)
        {
            <section id="post @post.Id">
                <article class="blogPost">
                    <header>
                        <h2>@post.Headline</h2>
                        <p>Category: @Html.ActionLink(post.Category.ToString(), "GetPostsByCategory", "Search", new { category = (int)post.Category }, null)</p>
                        <p>
                            Posted on <time datetime="2009-06-29T23:31+01:00">@post.Timestamp</time> by <a href="@post.Website">@post.Author</a> - <a href="#comments @post.Id">
                                @{if (post.Comments != null)
                                {<label id="commentCounter @post.Id">@post.Comments.Count</label>}
                                else
                                { <label id="commentCounter @post.Id">0</label> }} comments
                            </a>
                        </p>
                    </header>
                    <div>
                        @post.Content
                    </div>
                    @{
            if (File.Exists(Server.MapPath("~/Uploads/" + post.Id + ".png")))
            {
                <img src="~/Uploads/@(post.Id).png" />
            }
                    }

                    @{
            if (File.Exists(Server.MapPath("~/Uploads/" + post.Id + ".mp4")))
            {
                <video controls="controls">
                        <source src="~/Uploads/@(post.Id).mp4" type="video/mp4" />
                    </video>
                }
                        }
                    </article>
                </section>
                <section id="comments @post.Id" class="comments">
                    @{
                if (post.Comments != null)
                {
                    foreach (ShauliBlog.Models.Comment currComment in post.Comments)
                    {
                        <article>
                            <header>
                                <a href="@currComment.Website">@currComment.Headline by @currComment.Author</a> on <time datetime="2009-06-29T23:35:20+01:00">@currComment.Timestamp</time>
                            </header>
                            <p>@currComment.Content</p>

                        </article>
                    }
                }
                    }
                </section>
                <form method="post" class="addCommentForm">
                    <div class="form-horizontal">
                        <h4>Add your comment:</h4>
                        <hr>
                        <div class="form-group">
                            <input value="@post.Id" data-val="true" id="PostId" name="PostId" type="hidden" />
                        </div>

                        <div class="form-group">
                            <label class="control-label col-md-2" for="Headline">Headline</label>
                            <input class="text-box single-line" data-val="true" id="Headline" name="Headline" type="text" required />
                        </div>

                        <div class="form-group">
                            <label class="control-label col-md-2" for="Author">Author</label>
                            <input type="text" id="Author" name="Author" class="text-box single-line" required />
                        </div>

                        <div class="form-group">
                            <label class="control-label col-md-2" for="Website">Author's website</label>
                            <input type="text" class="text-box single-line" id="Website" name="Website" required />
                        </div>

                        <div class="form-group">
                            <label class="control-label col-md-2" for="Content">Content</label>
                            <textarea id="Content" name="Content" class="text-box multi-line" required></textarea>
                        </div>

                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-10">
                                <input type="submit" value="Create" class="btn btn-default" />
                            </div>
                        </div>
                    </div>
                </form>


            }
        }
    </div>

    <aside>
        <section>
            <header>
                <h3>@Html.ActionLink("Categories", "Categories", "Statistics")</h3>
            </header>
            <ul>
                <li>@Html.ActionLink("Sport", "GetPostsByCategory", "Search", new { category = (int)ShauliBlog.Models.Category.Sport }, null)</li>
                <li>@Html.ActionLink("Blog", "GetPostsByCategory", "Search", new { category = (int)ShauliBlog.Models.Category.Blog }, null)</li>
                <li>@Html.ActionLink("News", "GetPostsByCategory", "Search", new { category = (int)ShauliBlog.Models.Category.News }, null)</li>
                <li>@Html.ActionLink("Entertainment", "GetPostsByCategory", "Search", new { category = (int)ShauliBlog.Models.Category.Entertainment }, null)</li>
            </ul>
        </section>
    </aside>